const Strings = {
	"bookName": {
		bg: "Книгата Урантия",
		cs: "Kniha Urantia",
		da: "Urantia Bogen",
		de: "Das Urantia Buch",
		el: "Το Βιβλίο της Ουράντια",
		en: "The Urantia Book",
		es: "El Libro de Urantia",
		et: "Urantia raamat",
		fa: "کتاب یورنشیا",
		fi: "Urantia-kirja",
		fr: "Le Livre d’Urantia",
		he: "הספר של אורנטיה",
		hu: "Az Urantia könyv",
		id: "Buku Urantia",
		it: "Il Libro di Urantia",
		ja: "ウランティア ブック",
		ko: "유란시아 서",
		lt: "Urantijos Knyga",
		nl: "Het Urantia Boek",
		pl: "Księga Urantii",
		pt: "O Livro de Urântia",
		ro: "Cartea Urantia",
		ru: "Книга Урантии",
		sv: "Urantiaboken",
		tr: "Urantia’nın Kitabı"
	},
	"bookPart0": {
		bg: "Предисловие",
		cs: "Předmluva",
		da: "Forord",
		de: "Vorwort",
		el: "πρόλογο",
		en: "Foreword",
		es: "Prólogo",
		es1993: 'Prólogo',
		es2021: 'Prólogo',
		et: "Eessõna",
		fa: "پیشگفتار",
		fi: "Esipuhe",
		fr: "Introduction",
		he: "הקדמה",
		hu: "Előszó",
		id: "Pengantar",
		it: "Introduzione",
		ja: "序文",
		ko: "머리말",
		lt: "Įvadas",
		nl: "Voorwoord",
		pl: "Przedmowa",
		pt: "Introdução",
		ro: "Introducere",
		ru: "Предисловие",
		sv: "Förord",
		tr: "Önsöz"
	},
	"bookPart1": {
		bg: "ЧАСТ I - Централната и свръхвселените",
		cs: "Díl I. - Střední vesmír a supervesmír",
		da: "Del I - Kapitel det Centrale og Superuniverserne",
		de: "Teil I - Das Zentraluniversum und Superuniversen",
		el: "Μέρος Ι. - Το κεντρικό σύμπαν και τα υπερσύμπαντα",
		en: "Part I - The Central and Superuniverses",
		es: "Primera Parte - El Universo Central y los Superuniversos",
		es1993: 'PARTE I - El Universo Central y los Superuniversos',
		es2021: 'Parte I - El universo central y los superuniversos',
		et: "I OSA - Keskne universum ja superuniversumid",
		fa: "قسمت اول - جهان مرکزی و ابرجهانها",
		fi: "I OSA. - Keskusuniversumi ja superuniversumit",
		fr: "Partie I - L’Univers Central et les Superunivers",
		he: "חלק I - היקום המרכזי ויקומי העל",
		hu: "I. RÉSZ - A központi világegyetem és a felsőbb-világegyetemek",
		id: "BAGIAN I - Alam Semesta Sentral dan Super",
		it: "Parte I - L’Universo Centrale ed I Superuniversi",
		ja: "第I部 宇宙の中心と超銀河団について",
		ko: "제 1 부. 중앙 우주와 초우주",
		lt: "I DALIS - Centrinė Visata ir Supervisatos",
		nl: "DEEL I - Het Centrale Universum en de Superuniversa",
		pl: "CZĘŚĆ I - Wszechświat Centralny i Superwszechświaty",
		pt: "PARTE I - O Universo Central e os Superuniversos",
		ro: "Partea I - Universul Central şi Supraunversurile",
		ru: "Часть I - Центральная Вселенная и Сверхвселенных",
		sv: "DEL I - Centraluniversumet och superuniverserna",
		tr: "Kısım I / Bölüm 1 - Merkezi ve Aşkın Evrenleri"
	},
	"bookPart1Desc": {
		bg: "Подготвена от Уверския Корпус на личностите на свръхвселената, упълномощени от Извечно Древните на Орвонтон.",
		cs: "Podpořeno Sborem Osobností na Uverse jednajících na základě pověření Věčně Moudrých Orvontonu.",
		da: "Udarbejdet med støtte af et Uversa Korps af Superunivers Personligheder, med bemyndigelse af Orvontons Dagenes Ældste.",
		de: "Verfasst von einem Korps superuniverseller Persönlichkeiten aus Uversa, das mit Vollmacht der Ältesten der Tage von Orvonton handelte.",
		el: "(υποστηρίχθηκε από ένα σώμα υπερσυμπαντικών προσωπικοτήτων της ουβέρσα οι οποίες λειτουργούν εξουσιοδοτημένες από τους αρχαίους των ημερών του Όρβοντον.)",
		en: "Sponsored by a Uversa Corps of Superuniverse Personalities acting by authority of the Orvonton Ancients of Days",
		es: "Patrocinado por un Cuerpo de Personalidades Superuniversales de Uversa que actúa por autorización de los Ancianos de los Días de Orvonton.",
		es1993: "Auspiciada por un Cuerpo de Personalidades Superuniversales de Uversa que actúan por la autoridad de los Ancianos de los Días de Orvonton.",
		es2021: "Patrocinado por un cuerpo de personalidades superuniversales de Uversa que actúa por autorización de los Ancianos de los Días de Orvonton.",
		et: "Esitanud Superuniversumi Isiksuste Uversa Korpus Orvontoni Päevilt Vanade volitusel.",
		fa: "مسئولیت این مقالات به عهدۀ یک گروه یووِرسا متشکل از شخصیتهای ابرجهان است که با اجازۀ قدمای ایامهای اُروانتان عمل می‌کنند. ",
		fi: "Toimituksesta huolehti uversalainen superuniversumipersoonallisuuksien ryhmä, joka toimi Orvontonin Päivien Muinaisten antamin valtuuksin.",
		fr: "Parrainée par un Corps de Personnalités Superuniverselles agissant par autorité des Anciens des Jours d’Orvonton.",
		he: "בחסות סגל אישיויות של יקום העל מאוורסה הפועל בסמכות עתיקי היומין של אורוונטון",
		hu: "Ezen írások összeállítását egy, az orvontoni Nappalok Elődeinek felhatalmazása alapján működő, felsőbb-világegyetemi személyiségekből álló uverszai testület hitelesítette.",
		id: "Disponsori oleh suatu Korps Kepribadian Alam Semesta Super dari Uversa yang bertindak berdasarkan wewenang dari Yang Purba Harinya Orvonton.",
		it: "Patrocinata da un Corpo di Personalità Superuniversali di Uversa agente per autorità degli Antichi dei Giorni di Orvonton.",
		ja: "本セクションは、オルヴォントン神の権威によって活動する超銀河団の中心天体であるウヴェルサの後援を受けています",
		ko: "오르본톤의 옛적부터 늘 계신 이들의 권한을 받아 활동하는 유버르사의 초우주 성격자 군단의 후원을 받았다",
		lt: "Parengta Supervisatos Asmenybių Uversos Korpuso, veikiančio įgaliojus Orvontono Dienų Seniesiems.",
		nl: "Onder verantwoordelijkheid van een Uversa-korps van Superuniversum-Persoonlijkheden die handelen op gezag van de Ouden der Dagen van Orvonton.",
		pl: "Przygotowano pod nadzorem korpusu osobowości superwszechświatowych z Uversy, działających z upoważnienia Pradawnych Czasu z Orvontonu.",
		pt: "Auspiciada por um corpo de personalidades de Uversa, atuando por autorização dos Anciãos dos Dias de Orvonton.",
		ro: "Sponsorizat de un Corp din Uversa de Personalităţi ale Superuniversului acţionînd prin autoritatea Celor Vechi de Zile din Orvonton.",
		ru: "Подготовлено Увeрсским Корпусом личностей сверхвселенной, уполномоченных Древними Дней Орвонтона.",
		sv: "Avfattad under beskydd av en Uversa-kår bestående av auperuniversumpersonligheter med bemyndiagande av Dagarnas Forna i Orvonton.",
		tr: "Yüksek Evren Kişilikleri Topluluğun Başı tarafından Urantia’daki Cennetin İlahları ve kâinatın âlemlerinin tümü hususundaki doğruları yansıtmak için atanan Kutsal bir Orvonton Danışmanı tarafından yazılmıştır."
	},
	"bookPart2": {
		bg: "ЧАСТ II - Локалната вселена",
		cs: "Díl II. - Lokální Vesmír",
		da: "Del II - Lokaluniverset",
		de: "Teil II - Das Lokaluniversum",
		el: "Μέρος II. - Το τοπικό σύμπαν",
		en: "Part II - The Local Universe",
		es: "Segunda Parte - El Universo Local",
		es1993: 'PARTE II - El Universo Local',
		es2021: 'Parte II - El universo local',
		et: "II OSA - Kohalik universum",
		fa: "قسمت دوم - جهان محلی",
		fi: "II OSA. - Paikallisuniversumi",
		fr: "Partie II - L’Univers Local",
		he: "חלק II - היקום המקומי",
		hu: "II. RÉSZ - A helyi világegyetem",
		id: "BAGIAN II - Alam Semesta Lokal",
		it: "Parte II - L’Universo Locale",
		ja: "第II部 小銀河団について",
		ko: "제 2 부. 지역 우주",
		lt: "II DALIS - Vietinė Visata",
		nl: "DEEL II - Het Plaatselijk Universum",
		pl: "CZĘŚĆ II - Wszechświat Lokalny",
		pt: "PARTE II - O Universo Local",
		ro: "Partea a II a - Universul local",
		ru: "Часть II - Локальная Вселенная",
		sv: "DEL II - Lokaluniversumet",
		tr: "Kısım II / Bölüm 2 - Yerel Evrenler"
	},
	"bookPart2Desc": {
		bg: "Подготвено от Небадонския Корпус на Личностите на Локалната Вселена, упълномощени от Гавраил Салвингтонски.",
		cs: "Podpořeno Sborem Vesmírných Osobností Nebadonu jednajících na základě pověření Gabriela ze Salvigtonu.",
		da: "Udarbejdet med støtte af et korps af personligheder fra lokaluniverset Nebadon - med bemyndigelse af Gabriel i Salvington.",
		de: "Verfasst von einem Korps lokaluniverseller Persönlichkeiten, das mit Vollmacht Gabriels von Salvington handelte.",
		el: "υποστηρίχθηκε από ένα σώμα προσωπικοτήτων τοπικών συμπάντων του νέβαδον, με την εξουσιοδότηση του γαβριήλ του σάλβινγκτον.",
		en: "Sponsored by a Nebadon Corps of Local Universe Personalities acting by authority of Gabriel of Salvington",
		es: "Patrocinado por un Cuerpo de Personalidades del Universo Local de Nebadon que actúa por autorización de Gabriel de Salvington.",
		es1993: "Auspiciada por un Cuerpo de Personalidades del Universo Local de Nebadon que actúan por autoridad de Gabriel de Salvington.",
		es2021: "Patrocinado por un cuerpo de personalidades del universo local de Nebadon que actúa por autorización de Gabriel de Salvington.",
		et: "Esitanud Kohaliku Universumi Isiksuste Nebadoni Korpus Salvingtoni Gabrieli volitusel.",
		fa: " مسئولیت این مقالات به عهدۀ یک گروه نِبادان متشکل از شخصیتهای جهان محلی است که با اجازۀ جبرئیل سَلوینگتون عمل مکنند.",
		fi: "Laatinut Nebadonin paikallisuniversumin persoonallisuuksista koostunut ryhmä, joka toimi Salvingtonin Gabrielin valtuuttamana.",
		fr: "Parrainée par un Corps de Personnalités de l’Univers Local de Nébadon agissant sous l’autorité de Gabriel de Salvington.",
		he: "בחסות סגל אישיויות של היקום המקומי מנבאדון הפועל בסמכות גבריאל מסאלווינגטון",
		hu: "Ezen írások összeállítását egy, a szalvingtoni Gábriel felhatalmazása alapján működő, helyi világegyetemi személyiségekből álló nebadoni testület hitelesítette.",
		id: "Disponsori suatu Korps Kepribadian Alam Semesta Lokal dari Nebadon yang bertindak berdasarkan wewenang dari Gabriel Salvington.",
		it: "Patrocinata da un Corpo di Personalità dell’Universo Locale di Nebadon agente per autorità di Gabriele di Salvington.",
		ja: "本セクションは、大天使ガブリエルの権威によって活動する小銀河団の一つであるネバドンの後援を受けています。",
		ko: "구원자 별의 가브리엘에서 권한을 받아 활동하는 네바돈 지역 우주 성격자 군단의 후원을 받았다",
		lt: "Parengta Vietinės Visatos Asmenybių Nebadono Korpuso, veikiančio įgaliojus Salvingtono Gabrieliui.",
		nl: "Verzorgd door een Nebadon-korps van Persoonlijkheden uit het Plaatselijk Universum, handelend op gezag van Gabriël van Salvington.",
		pl: "Przygotowano pod nadzorem korpusu osobowości z wszechświata lokalnego Nebadonu, działających z upoważnienia Gabriela z Salvingtonu.",
		pt: "Auspiciada por um Corpo de Personalidades do Universo Local de Nebadon, atuando por autorização de Gabriel de Salvington.",
		ro: "Prezentat de un Corp din Nebadon al Universului Local Personalităţi activând cu autoritatea lui Gabriel al Salvingtonului.",
		ru: "Подготовлено Небадонским Корпусом личностей локальной вселенной, уполномоченных Гавриилом Салвингтонским.",
		sv: "Avfattad under beskydd av en Nebadon-kår av personligheter i lokaluniversumet med bemyndigqnde av Gabriel i Salvington.",
		tr: "Salvington'lu Gabriel'in otoritesi tarafından hareket eden Yerel Evren Kişilikleri Nebadon Birliği sponsorluğu tarafından yazılmıştır."
	},
	"bookPart3": {
		bg: "ЧАСТ III - Историята на Урантия",
		cs: "Díl III. - Historie Urantie",
		da: "Del III - Urantias Historie",
		de: "Teil III - Die Geschichte Urantias",
		el: "Μέρος ΙΙΙ. - Η ιστορία της Ουράντια",
		en: "Part III - The History of Urantia",
		es: "Tercera Parte - La Historia de Urantia",
		es1993: 'PARTE III - La Historia de Urantia',
		es2021: 'Parte III - Historia de Urantia',
		et: "III OSA - Urantia ajalugu",
		fa: "قسمتسوم - تاریخ یورنشیا",
		fi: "III OSA. - Urantian historia",
		fr: "Partie III - L’Histoire D’Urantia",
		he: "חלק III - ההיסטוריה של אורנטיה",
		hu: "III. RÉSZ - Az Urantia története",
		id: "BAGIAN III - Sejarah Urantia",
		it: "Parte III - La Storia di Urantia",
		ja: "第III部 ウランティア（地球）の歴史について",
		ko: "제 3 부. 유란시아의 역사",
		lt: "III DALIS - Urantijos Istorija",
		nl: "DEEL III - De Geschiedenis van Urantia",
		pl: "CZĘŚĆ III - Historia Urantii",
		pt: "PARTE III - A História de Urântia",
		ro: "Partea a III a - Istoria Urantia",
		ru: "Часть III - История Урантии",
		sv: "DEL III - Urantias historia",
		tr: "Kısım III / Bölüm 3 - Urantia’nın Tarihi"
	},
	"bookPart3Desc": {
		bg: "Настоящите повествувания бяха подготовени от Корпуса на личностите на локалната вселена, упълномощени от Гавраил Салвингтонски.",
		cs: "Tyto kapitoly jsou podpořeny Sborem Osobností Lokálního Vesmíru jednajících na základě pověření Gabriela ze Salvingtonu.",
		da: "Disse kapitler er støttet af et korps af personligheder fra det lokale univers, autoriseret af Gabriel af Salvington.",
		de: "Diese Schriften wurden von einem Korps lokaluniverseller Persönlichkeiten verfasst, das mit Vollmacht Gabriels von Salvington handelte.",
		el: "τα φύλλα αυτά υποστηρίχθηκαν από ένα σώμα προσωπικοτήτων του τοπικού σύμπαντος, οι οποίες ενεργούν εξουσιοδοτημένες από τον γαβριήλ του σάλβινγκτον.",
		en: "These papers were sponsored by a Corps of Local Universe Personalities acting by authority of Gabriel of Salvington",
		es: "Estos documentos fueron patrocinados por un Cuerpo de Personalidades del Universo Local que actúa por autorización de Gabriel de Salvington.",
		es1993: "Estos documentos fueron auspiciados por un Cuerpo de Personalidades del Universo Local que actúan por autoridad de Gabriel de Salvington.",
		es2021: "Estos documentos fueron patrocinados por un cuerpo de personalidades del universo local que actúa por autorización de Gabriel de Salvington.",
		et: "Käesolevad kirjad on esitanud Kohaliku Universumi Isiksuste Korpus Salvingtoni Gabrieli volitusel.",
		fa: "مسئولیت این مقالات به عهدۀ یک گروه از شخصیتهای جهان محلی است که با اجازۀ جبرئیل سلوینگتون عمل می‌کنند.",
		fi: "Nämä luvut laaditutti paikallisuniversumin persoonallisuuksista koostunut ryhmä, joka toimi Salvingtonin Gabrielin valtuuttamana.",
		fr: "Ces fascicules furent parrainés par un Corps de Personnalités de l’Univers Local agissant par autorité de Gabriel de Salvington.",
		he: "מסמכים אלה הוכנו בחסות סגל אישיויות של היקום המקומי הפועל בסמכות גבריאל מסאלווינגטון",
		hu: "Ezen írások összeállítását egy, a szalvingtoni Gábriel felhatalmazása alapján működő, helyi világegyetemi személyiségekből álló testület hitelesítette.",
		id: "Makalah-makalah ini disponsori oleh suatu Korps Kepribadian Alam Semesta Lokal yang bertindak berdasarkan wewenang dari Gabriel Salvington.",
		it: "Questi fascicoli sono stati patrocinati da un Corpo di Personalità dell’Universo Locale agente per autorità di Gabriele di Salvington.",
		ja: "本セクションは、大天使ガブリエルの権威によって活動する小銀河団の後援を受けています。",
		ko: "구원자 별의 가브리엘의 권한으로 활동하는 지역 우주 성격자 군단이 이 논문집을 후원하였다",
		lt: "Šiuos dokumentus parengė Vietinės Visatos Asmenybių Korpusas, veikiantis Salvingtono Gabrielio įgaliojimu.",
		nl: "Deze verhandelingen zijn verzorgd door en Korps Persoonlijkheden van het Plaatselijk Universum, op gezag van Gabriël van Salvington.",
		pl: "Przekazy te były przygotowane pod nadzorem korpusu osobowości z wszechświata lokalnego, działających z upoważnienia Gabriela z Salvingtonu.",
		pt: "Esses documentos foram auspiciados por um Corpo de Personalidades do Universo Local, atuando por autorização de Gabriel de Salvington.",
		ro: "Aceste capitole au fost prezentate de un Corp de Personalităţi ale Universului Local acţionând prin autoritatea lui Gabriel din Salvington.",
		ru: "Настоящие документы были подготовлены Корпусом личностей локальной вселенной, уполномоченных Гавриилом Салвингтонским.",
		sv: "Dessa kapitel avfattades under beskydd af en kår av personligheter i lokaluniversumet med bemyndigande av Gabriel i Salvington.",
		tr: "Bu bildiriler, Salvington'lu Gabriel'in otoritesi tarafından hareket eden Yerel Evren Kişilikleri Birliği tarafından desteklenmiştir."
	},
	"bookPart4": {
		bg: "ЧАСТ IV - Животът и ученията на Иисус",
		cs: "Díl IV. - Život a učení Ježíše",
		da: "Del IV - Jesu Liv og Lære",
		de: "Teil IV - Das Leben und die Lehren Jesu",
		el: "Μέρος IV. - H ζωή και η διδασκαλία του Ιησού",
		en: "Part IV - The Life and Teachings of Jesus",
		es: "Cuarta Parte - La Vida y las Enseñanzas de Jesús",
		es1993: 'PARTE IV - La Vida y las Enseñanzas de Jesus',
		es2021: 'Parte IV - Vida y enseñanzas de Jesús',
		et: "IV OSA - Jeesuse elu ja õpetused",
		fa: "قسمت چهارم - زندگی و آموزشهای عیسی",
		fi: "IV OSA. - Jeesuksen elämä ja opetukset",
		fr: "Partie IV - La Vie et les Enseignements de Jésus",
		he: "חלק IV - חייו של ישוע ותורתו",
		hu: "IV. RÉSZ - Jézus élete és tanításai",
		id: "BAGIAN IV - Kehidupan dan Ajaran Yesus",
		it: "Parte IV - La Vita e gli Insegnamenti Di Gesù",
		ja: "第IV部 キリストの教えとその生涯について",
		ko: "제 4 부. 예수의 일생과 가르침",
		lt: "IV DALIS - Jėzaus Gyvenimas ir Mokymai",
		nl: "DEEL IV - Het Leven en Onderricht van Jezus",
		pl: "CZĘŚĆ IV - Życie i Nauki Jezusa",
		pt: "PARTE IV - A Vida e os Ensinamentos de Jesus",
		ro: "Partea a IV a - Viaţa şi învăţăturile lui Iisus",
		ru: "Часть IV - Жизнь и Учения Иисуса",
		sv: "DEL IV - Jesu liv och förkunnelse",
		tr: "Kısım IV / Bölüm 4 - İsa’nın Hayatı ve Öğretileri"
	},
	"bookPart4Desc": {
		bg: "Настоящият раздел беше подготвен от комисия от дванадесет промеждутъчни създания на Урантия, трудили се под наблюдението на Мелхиседек, ръководител на комисията по откровенията. | В основата на повествуванията е положена Информация, предоставена от вторично промеждутъчно създание, някога изпълнявало задълженията на свръхчовешки хранител на апостол Андрей.",
		cs: "Tyto kapitoly jsou podpořeny komisí dvanácti midbytostí naší planety Urantie jednajících pod dohledem vedoucího zjevení Melkísedeka. | Podklady pro toto vyprávění byly dodány sekundární midbytostí, která byla toho času přidělena nadlidskému dohledu nad Apoštolem Ondřejem.",
		da: "De følgende kapitel blev udarbejdet af en kommission af tolv Urantia mellemvæsener som virkede under opsyn af en Melkisedek som ledede åbenbaringseprojektet. | Grundlaget for denne beretning blev leveret af en anden gradens mellemvæsen som engang var betroet det overmenneskelige tilsyn med apostelen Andreas.",
		de: "Diese Schriftengruppe wurde von einer Kommission von zwölf Mittlern Urantias verfasst, die unter Aufsicht eines Melchisedek-Offenbarungsleiters handelte. | Die Grundlage zu diesem Bericht lieferte ein sekundärer Mittler, der einst mit der übermenschlichen Obhut des Apostels Andreas beauftragt war.",
		el: "Αυτή η ομάδα εγγράφων χορηγήθηκε από μια επιτροπή δώδεκα μεσοδιάστατων της Ουράντια, ενεργούντων υπό την επίβλεψη ενός αποκαλυπτικού διευθύνοντα Μελχισεδέκ. | Η βάση αυτής της αφήγησης παρασχέθηκε από έναν δευτερεύοντα μεσοδιάστατο στον οποίον είχε κάποτε ανατεθεί η υπεράνθρωπη φροντίδα του Αποστόλου Ανδρέα>",
		en: "This group of papers was sponsored by a commission of twelve Urantia midwayers acting under the supervision of a Melchizedek revelatory director. | The basis of this narrative was supplied by a secondary midwayer who was onetime assigned to the superhuman watchcare of the Apostle Andrew.",
		es: "Este grupo de documentos fue patrocinado por una comisión de doce intermedios de Urantia que actuaba bajo la supervisión de un Melquisedek director de la revelación. | La base de esta narración fue suministrada por un intermedio secundario que en otro tiempo estuvo asignado a la custodia superhumana del Apóstol Andrés.",
		es1993: "Esta colección de documentos fue auspiciada por una comisión de doce seres intermedios de Urantia que actúan bajo la supervisión de un director Melquisedek de revelación. | La base de esta narrativa provino de un ser intermedio secundario a quien cierta vez fue encomendada la vigilancia y custodia superhumana de el Apóstol Andrés.",
		es2021: "Este grupo de documentos fue patrocinado por una comisión de doce seres intermedios de Urantia bajo la supervisión de un Melquisedec director de revelación. | La base de esta narración fue provista por un ser intermedio secundario asignado a la custodia sobrehumana del apóstol Andrés.",
		et: "Selle osa kirjad on esitanud kaheteistkümnest Urantia keskteelisest koosnev ilmutuskomisjon, kelle tegevust juhendas Melkisedekist juht. | Jutustuse aluseks olevad andmed on saadud teiseselt keskteeliselt, kes oli omal ajal seatud apostel Andrease üleinimlikuks kaitsjaks.",
		fa: "مسئولیت این گروه از مقالات به عهدۀ کمیسیونی متشکل از دوازده مخلوق بینابینیِ یورنشیا است که تحت سرپرستی یک مدیر آشکارسازی ملک صادق عمل مکنند. |  مبنای این نوشته توسط یک مخلوق بینابینیِ ثانویه که روزگاری به مراقبت فوق بشری از آندریاس رسول گمارده شده بود فراهم گردید.",
		fi: "Näiden lukujen toimittamisesta huolehti kahdestatoista urantialaisesta keskiväliolennosta koostunut komissio, joka toimi totuuden julkituomista ohjanneen Melkisedekin valvonnassa. | Tämän kertomuksen pohja-aineisto on saatu eräältä toisasteiselta keskiväliolennolta, joka aikanaan toimi apostoli Andreaksesta huolehtivana ihmisen yläpuolista tasoa edustavana suojelijana.",
		fr: "Ce groupe de fascicules fut parrainé par une commission de douze médians d’Urantia agissant sous la supervision d’un Melchizédek directeur de la révélation. | La base de ce récit a été fournie par un médian secondaire qui fut jadis chargé de la surveillance suprahumaine de l’Apôtre André.",
		he: "קבוצת מסמכים זו הוכנה בחסות וועדה בת שניים עשר אמצעיונים מאורנטיה הפועלת תחת פיקוחו של מנהל התגלות מלכי-צדק. |  התיאור מבוסס על עדותו של אמצעיוני שניוני שבעבר השגיח באופן על-אנושי על השליח אנדראס. ",
		hu: "Ezen írások összeállítását egy, az egyik Melkizedek kinyilatkoztatási igazgató felügyelete alatt működő, tizenkét fős urantiai közteslény-bizottság hitelesítette. | A beszámoló alapját egy olyan másodfajú közteslény szolgáltatta, aki András apostol felett a szellemvilági óvó-figyelő szolgálatot egykor ellátta.",
		id: "Kelompok makalah ini disponsori oleh suatu komisi dua belas makhluk tengah (midwayers) Urantia yang bertindak di bawah pengawasan dari direktur pewahyuan Melkisedek. | Dasar untuk kisah ini disediakan oleh sesosok makhluk tengah sekunder yang pernah ditugasi untuk pengawasan supramanusiawi terhadap Rasul Andreas.",
		it: "Questo gruppo di fascicoli è stato patrocinato da una commissione di dodici intermedi di Urantia agente sotto la supervisione di un direttore di rivelazione Melchizedek. | La base di questo racconto è stata fornita da un intermedio secondario che fu un tempo assegnato alla sorveglianza superumana dell’apostolo Andrea.",
		ja: "本セクションは、啓示者メルキゼデクの監督の下に活動する12名のウランティア中途者（midwayers）の後援を受けています。 |  この物語のあらすじは、かつて使徒アンドリューの監視を行っていた二次中途者によってもたらされました ",
		ko: "이 논문집은 멜기세덱 계시 지휘자의 감독 밑에서 행동하는 유란시아의 열두 중도자로 구성된 위원회의 후원을 받았다. | 이 이야기의 근거는 한때 사도 안드레를 초인간적으로 보호하는 데 배치된 한 2차 중도자가 제공하였다.",
		lt: "Šitą dokumentų grupę parengė Urantijos tarpinių būtybių komisija iš dvylikos narių, veikusi apreiškimo vadovo Melkizedeko priežiūroje. | Šito pasakojimo pagrindą pateikė viena iš antrinių tarpinių būtybių, kuri kažkada buvo paskirta Apaštalo Andriejaus viršžmogiškajai apsaugai.",
		nl: "Deze groep verhandelingen is verzorgd door een commissie van twaalf middenwezens van Urantia, handelend onder toezicht van een Melchizedek die leiding gaf aan deze openbaring. | De basis voor dit relaas werd verschaft door een secundair middenwezen dat eens was belast met de bovenmenselijke zorgende hoede over de Apostel Andreas.",
		pl: "Ta grupa przekazów przygotowana została pod nadzorem komisji, złożonej z dwunastu pośrednich z Urantii, działających pod nadzorem Melchizedeka, szefa objawienia. | Podstawy narracji dostarczył pośredni wtórny, który swego czasu był przydzielony do nadludzkiej opieki Apostoła Andrzeja.",
		pt: "Esse grupo de documentos foi auspiciado por uma comissão de doze Seres Intermediários de Urântia atuando sob a supervisão de um diretor Melquisedeque de revelação. | A base dessa narrativa foi fornecida por um ser intermediário secundário que tinha sido designado anteriormente para a custódia suprahumana do Apóstolo André.",
		ro: "Acest grup de capitole a fost garantat de o comisie de doisprezece mediani ai Urantiei care acţionează sub supravegherea unui Melchisedec conducător de revelaţie. | Baza acestei povestiri a fost furnizată de un median secundar care a fost cândva însărcinat cu supravegherea supraumană a Apostolului Andrei.",
		ru: "Данный раздел был подготовлен комиссией из двенадцати промежуточных созданий Урантии, трудившихся под наблюдением Мелхиседека, руководителя комиссии откровения. | В основу повествования положена информация, предоставленная вторичным промежуточным созданием, некогда исполнявшим обязанности сверхчеловеческого хранителя апостола Андрея. | ",
		sv: "Dessa kapitel avfattades under beskydd av en kommission om tolv Urantia-mellanvarelser som fungerade under övervakning af den Melkisedk som ledde uppenbarelseprojektet. | Basmaterialet för denna berättelse tillhandahöll en andra gradens mellanvarelse som en gång var förordnad att på övermänsklig nivå övervaka apostlen Andreas.",
		tr: "Bu bildiri grubu, bir Melçizedek açığa çıkarıcı yönetmenin denetimi altında hareket eden on iki Urantia yarı-ölümlüden oluşan bir komisyon tarafından desteklendi. | Bu anlatının temeli, bir zamanlar Havari Andrew'un insanüstü gözetimine atanan ikincil bir yarı çocuk tarafından sağlandı."
	},
	"bookMasterYear": {
		bg: "2014",
		cs: "2019",
		da: "2015",
		de: "2015",
		el: "2018",
		en: "1955",
		es: "2009",
		et: "2010",
		fa: "2018",
		fi: "1993",
		fr: "2014",
		he: "2018",
		hu: "2010",
		id: "2020",
		it: "2006",
		ja: "2015",
		ko: "2016",
		lt: "2004",
		nl: "1997",
		pl: "2010",
		pt: "2007",
		ro: "2004",
		ru: "1997",
		sv: "2010",
		tr: "2021"
	},
	"bookAbb": {
		bg: "КУ",
		cs: "KU",
		da: "UB",
		de: "UB",
		el: "ΒΟ",
		en: "UB",
		es: "LU",
		et: "Ur",
		fa: "یور",
		fi: "U-k",
		fr: "LU",
		he: "או",
		hu: "Uk",
		id: "BU",
		it: "LU",
		ja: "ウラ",
		ko: "유란",
		lt: "UK",
		nl: "UB",
		pl: "KU",
		pt: "LU",
		ro: "CU",
		ru: "КУ",
		sv: "Ub",
		tr: "UK"
	},
	"bookPaper": {
		bg: "Документ",
		cs: "Kapitola",
		da: "Kapitel",
		de: "Schrift",
		el: "Εγγραφο",
		en: "Paper",
		es: "Documento",
		et: "Kiri",
		fa: "مقالۀ",
		fi: "Luku",
		fr: "Fascicule",
		he: "מסמך",
		hu: "írás",
		id: "Makalah",
		it: "Fascicolo",
		ja: "論文",
		ko: "제 {0} 편",
		lt: "Dokumentas",
		nl: "Verhandeling",
		pl: "Przekaz",
		pt: "Documento",
		ro: "Capitolul",
		ru: "Документ",
		sv: "Kapitel",
		tr: "Makale"
	},
	"bookPaperAbb": {
		bg: "Документ",
		cs: "Kap",
		da: "Kap",
		de: "Kap",
		el: "Εγγ",
		en: "Paper",
		es: "Doc",
		et: "Kiri",
		fa: "مقالۀ",
		fi: "Luku",
		fr: "Fasc",
		he: "מסמך",
		hu: "írás",
		id: "Mak",
		it: "Fasc",
		ja: "論文",
		ko: "편",
		lt: "Dok",
		nl: "Ver",
		pl: "Prz",
		pt: "Doc",
		ro: "Cap",
		ru: "Док",
		sv: "Kap",
		tr: "Mak"
	},
	"bookChapter": {
		bg: "глава",
		cs: "Kapitola",
		da: "Kapitel",
		de: "Kapitel",
		el: "Κεφάλαιο",
		en: "Chapter",
		es: "Capítulo",
		et: "Peatükk",
		fa: "فصل",
		fi: "Luku",
		fr: "Chapitre",
		he: "פֶּרֶק",
		hu: "Fejezet",
		id: "Bab",
		it: "Capitolo",
		ja: "章",
		ko: "장",
		lt: "Skyrius",
		nl: "Hoofdstuk",
		pl: "Rozdział",
		pt: "Capítulo",
		ro: "Capitol",
		ru: "Глава",
		sv: "Kapitel",
		tr: "Bölüm"
	},
	"bookIndexName": {
		bg: "Индекс",
		cs: "Index",
		da: "Indeks",
		de: "Index",
		el: "Δείκτης",
		en: "Index",
		es: "Índice",
		et: "Indeks",
		fa: "فهرست مطالب",
		fi: "Indeksi",
		fr: "Table des matières",
		he: "אינדקס",
		hu: "Index",
		id: "Indeks",
		it: "Indice",
		ja: "索引",
		ko: "색인",
		lt: "Indeksas",
		nl: "Inhoudsopgave",
		pl: "Indeks",
		pt: "Índice",
		ro: "Index",
		ru: "Индекс",
		sv: "Index",
		tr: "Dizin"
	},
	"bookExtIndexName": {
		bg: "Съдържание на книгата",
		cs: "Obsah knihy",
		da: "Indholdet af bogen",
		de: "Ausführliches Inhaltsverzeichnis",
		el: "Ο δείκτης επεκτάθηκε",
		en: "Index extended",
		es: "Indice extendido",
		et: "Raamatu sisukord",
		fa: "شاخص تمدید شد",
		fi: "Sisällysluettelo",
		fr: "Table des matières détaillée",
		he: "האינדקס מורחב",
		hu: "A könyv tartalomjegyzéke",
		id: "Isi Buku",
		it: "Contenuto del Libro",
		ja: "インデックス拡張",
		ko: "목차",
		lt: "Knygos turinys",
		nl: "Inhoudsopgave",
		pl: "Spis treści książki",
		pt: "Índice Detalhado",
		ro: "Conţinutul Cărţii",
		ru: "Содержание книги",
		sv: "Innehållsförteckning",
		tr: "Genişletilmiş Dizin"
	},
	"bookMultipleVersion": {
		bg: "Множествена версия",
		cs: "Více verzí",
		da: "Flere versioner",
		de: "Mehrfachversion",
		el: "Πολλαπλή έκδοση",
		en: "Multiple version",
		es: "Versión múltiple",
		et: "Mitu versiooni",
		fa: "نسخه چندگانه",
		fi: "Useita versioita",
		fr: "Version multiple",
		he: "גרסה מרובה",
		hu: "Több verzió",
		id: "Beberapa versi",
		it: "Versione multipla",
		ja: "複数バージョン",
		ko: "여러 버전",
		lt: "Keli versija",
		nl: "Meerdere versies",
		pl: "Wersja wielokrotna",
		pt: "Versão múltipla",
		ro: "Varianta multipla",
		ru: "Множественная версия",
		sv: "Flera versioner",
		tr: "Çoklu sürüm"
	},
	"bookSingleVersion": {
		bg: "Единична версия",
		cs: "Jediná verze",
		da: "Enkelt version",
		de: "Einzelversion",
		el: "Ενιαία έκδοση",
		en: "Single version",
		es: "Versión sencilla",
		et: "Üksikversioon",
		fa: "نسخه تک",
		fi: "Yksi versio",
		fr: "Version unique",
		he: "גרסה בודדת",
		hu: "Egyetlen változat",
		id: "Versi tunggal",
		it: "Versione singola",
		ja: "シングルバージョン",
		ko: "단일 버전",
		lt: "Viena versija",
		nl: "Enige versie",
		pl: "Wersja pojedyncza",
		pt: "Versão única",
		ro: "Versiune unică",
		ru: "Одиночная версия",
		sv: "Singelversion",
		tr: "Tek versiyon"
	},
	"bookLanguages": {
		bg: "Bulgarian",
		cs: "Czech",
		da: "Danish",
		de: "German",
		el: "Greek",
		en: "English",
		es: "Spanish",
		et: "Estonian",
		fa: "Farsi",
		fi: "Finnish",
		fr: "French",
		he: "Hebrew",
		hu: "Hungarian",
		id: "Indonesian",
		it: "Italian",
		ja: "Japanese",
		ko: "Korean",
		lt: "Lithuanian",
		nl: "Dutch",
		pl: "Polish",
		pt: "Portuguese",
		ro: "Romanian",
		ru: "Russian",
		sv: "Swedish",
		tr: "Turkish"
	},
	"enLanguage": {
		bg: "Английски",
		cs: "Angličtina",
		da: "Engelsk",
		de: "Englisch",
		el: "Αγγλικά",
		en: "English",
		es: "Inglés",
		et: "Inglise",
		fa: "انگلیسی",
		fi: "Englanti",
		fr: "Anglais",
		he: "אנגלית",
		hu: "Angol",
		id: "Inggris",
		it: "Inglese",
		ja: "英語",
		ko: "영국사람",
		lt: "Anglų",
		nl: "Engels",
		pl: "Angielski",
		pt: "Inglês",
		ro: "Engleză",
		ru: "Английский",
		sv: "Engelska",
		tr: "İngilizce"
	},
	"ownLanguage": {
		bg: "Български",
		cs: "Čeština",
		da: "Dansk",
		de: "Deutsch",
		el: "Ελληνικά",
		en: "English",
		es: "Español",
		et: "Eesti",
		fa: "فارسی",
		fi: "Suomi",
		fr: "Français",
		he: "עברית",
		hu: "Magyar",
		id: "Indonesian",
		it: "Italiano",
		ja: "日本語",
		ko: "한국어",
		lt: "Lietuvių",
		nl: "Nederlands",
		pl: "Polski",
		pt: "Português",
		ro: "Română",
		ru: "Русский",
		sv: "Svenska",
		tr: "Türkçe"
	},
	"foundation": {
		bg: "Фондация Урантия",
		cs: "Nadace Urantia",
		da: "Urantia Foundation",
		de: "Die Urantia Stiftung",
		el: "Ίδρυμα Ουράντια",
		en: "Urantia Foundation",
		es: "Fundación Urantia",
		et: "Urantia Sihtasutus",
		fa: "بنیاد یورنشیا",
		fi: "Urantia Foundationin",
		fr: "Urantia Foundation",
		he: "הקרן של אורנטיה",
		hu: "Urantia Alapítvány",
		id: "Yayasan Urantia",
		it: "Urantia Foundation",
		ja: "ウランティア財団",
		ko: "유란시아 재단",
		lt: "Urantijos Fondas",
		nl: "De Stichting Urantia",
		pl: "Fundacja Urantii",
		pt: "Fundação Urantia",
		ro: "Fundația Urantia",
		ru: "Фонд УРАНТИЯ",
		sv: "Urantia Foundation",
		tr: "Urantia Society of Greater New York"
	},
	"freedomain": {
		bg: "Книгата Урантия на английски език е обществено достояние в целия свят от 2006 г",
		cs: "Kniha Urantia v angličtině je od roku 2006 celosvětově Public Domain",
		da: "Urantia-bogen på engelsk er Public Domain på verdensplan siden 2006",
		de: "Das Urantia-Buch in englischer Sprache ist seit 2006 weltweit gemeinfrei",
		el: "Το βιβλίο Urantia στα αγγλικά είναι δημόσιος τομέας παγκοσμίως από το 2006",
		en: "The Urantia Book in English is Public Domain worldwide since 2006",
		es: "El Libro de Urantia en inglés es de dominio público en todo el mundo desde 2006",
		et: "Ingliskeelne Urantia raamat on alates 2006. aastast kogu maailmas avalik",
		fa: "کتاب Urantia به زبان انگلیسی از سال 2006 دامنه عمومی در سراسر جهان است",
		fi: "Englanninkielinen Urantia-kirja on ollut julkisessa käytössä maailmanlaajuisesti vuodesta 2006 lähtien",
		fr: "Le Livre d'Urantia en anglais est dans le domaine public mondial depuis 2006",
		he: "ספר אורנטיה באנגלית הוא נחלת הכלל ברחבי העולם מאז 2006",
		hu: "Az angol nyelvű Urantia könyv 2006 óta világszerte nyilvános",
		id: "Buku Urantia dalam bahasa Inggris adalah Domain Publik di seluruh dunia sejak 2006",
		it: "Il Libro di Urantia in inglese è di pubblico dominio in tutto il mondo dal 2006",
		ja: "英語の Urantia Book は、2006 年以来、世界中でパブリック ドメインです。",
		ko: "영어로 된 유란시아 책은 2006년부터 전 세계적으로 퍼블릭 도메인입니다.",
		lt: "Urantijos knyga anglų kalba yra vieša visame pasaulyje nuo 2006 m",
		nl: "Het Urantia Boek in het Engels is sinds 2006 wereldwijd Public Domain",
		pl: "Księga Urantii w języku angielskim jest domeną publiczną na całym świecie od 2006 roku",
		pt: "O Livro de Urântia em inglês é de domínio público em todo o mundo desde 2006",
		ro: "Cartea Urantia în limba engleză este Domeniu Public în întreaga lume din 2006",
		ru: "Книга Урантии на английском языке является общественным достоянием во всем мире с 2006 года.",
		sv: "Urantia-boken på engelska är Public Domain över hela världen sedan 2006",
		tr: "İngilizce Urantia Kitabı, 2006'dan beri dünya çapında Kamu Malıdır"
	},
	"translations": {
		bg: "Преводи:",
		cs: "Překlady:",
		da: "Oversættelser:",
		de: "Übersetzungen:",
		el: "Μεταφράσεις:",
		en: "Translations:",
		es: "Traducciones:",
		et: "Tõlked:",
		fa: "ترجمه ها:",
		fi: "Käännökset:",
		fr: "Traductions :",
		he: "תרגומים:",
		hu: "Fordítások:",
		id: "Terjemahan:",
		it: "Traduzioni:",
		ja: "翻訳:",
		ko: "번역:",
		lt: "Vertimai:",
		nl: "Vertalingen:",
		pl: "Tłumaczenia:",
		pt: "Traduções:",
		ro: "Traduceri:",
		ru: "Переводы:",
		sv: "Översättningar:",
		tr: "Çeviriler:"
	},
	"bibleName": {
		bg: "Библията",
		cs: "Bible",
		da: "Biblen",
		de: "Die Bibel",
		el: "Η Βίβλος",
		en: "The Bible",
		es: "La Biblia",
		et: "Piibel",
		fa: "کتاب مقدس",
		fi: "Raamattu",
		fr: "La Bible",
		he: "ביבליה",
		hu: "A Biblia",
		id: "Alkitab",
		it: "La Bibbia",
		ja: "聖書",
		ko: "성경",
		lt: "Biblija",
		nl: "De Bijbel",
		pl: "Biblia",
		pt: "A Bíblia",
		ro: "Biblia",
		ru: "Библия",
		sv: "Bibeln",
		tr: "İncil"
	},
	"bibleOldTestament": {
		bg: "Старият завет",
		cs: "Starý zákon",
		da: "Gamle Testamente",
		de: "Altes Testament",
		el: "Παλαιά Διαθήκη",
		en: "Old Testament",
		es: "Antiguo Testamento",
		et: "Vana Testament",
		fa: "عهد قديم",
		fi: "Vanha testamentti",
		fr: "L'Ancien Testament",
		he: "הברית הישנה",
		hu: "Ótestamentum",
		id: "Perjanjian Lama",
		it: "Vecchio Testamento",
		ja: "旧約聖書",
		ko: "구약 성서",
		lt: "Senas testamentas",
		nl: "Oude Testament",
		pl: "Stary Testament",
		pt: "Antigo Testamento",
		ro: "Vechiul Testament",
		ru: "Ветхий Завет",
		sv: "Gamla testamentet",
		tr: "Eski Antlaşma"
	},
	"bibleNewTestament": {
		bg: "Нов завет",
		cs: "Nový zákon",
		da: "Nye Testamente",
		de: "Neues Testament",
		el: "Καινή Διαθήκη",
		en: "New Testament",
		es: "Nuevo Testamento",
		et: "Uus Testament",
		fa: "عهد جديد",
		fi: "Uusi testamentti",
		fr: "Nouveau Testament",
		he: "עדות חדשה",
		hu: "Újtestamentum",
		id: "Perjanjian Baru",
		it: "Nuovo Testamento",
		ja: "新約聖書",
		ko: "신약 성서",
		lt: "Naujasis Testamentas",
		nl: "Nieuwe Testament",
		pl: "Nowy Testament",
		pt: "Novo Testamento",
		ro: "Noul Testament",
		ru: "Новый Завет",
		sv: "Nya testamentet",
		tr: "Yeni Antlaşma"
	},
	"bibleApocrypha": {
		bg: "апокриф",
		cs: "Apokryfy",
		da: "Apokryfer",
		de: "Apokryphen",
		el: "Απόκρυφα",
		en: "Apocrypha",
		es: "Apócrifos",
		et: "Apokrüüfid",
		fa: "آپوکریفا",
		fi: "Apokryfi",
		fr: "Apocryphes",
		he: "אפוקריפים",
		hu: "Jelenések könyve",
		id: "Tulisan yg diragukan pengarangnya",
		it: "Apocrifi",
		ja: "外典",
		ko: "외전",
		lt: "Apokrifai",
		nl: "Apocriefen",
		pl: "Apokryfy",
		pt: "Apócrifo",
		ro: "Apocrife",
		ru: "Апокрифы",
		sv: "De apokryfiska böckerna",
		tr: "Apokrif"
	},
	"bibleFullIndex": {
		bg: "Пълен индекс на Библията",
		cs: "Úplný rejstřík Bible",
		da: "Fuldt indeks over Bibelen",
		de: "Vollständiger Index der Bibel",
		el: "Πλήρες Ευρετήριο της Βίβλου",
		en: "Full Index of The Bible",
		es: "Índice completo de la Biblia",
		et: "Piibli täielik register",
		fa: "فهرست کامل کتاب مقدس",
		fi: "Raamatun täydellinen hakemisto",
		fr: "Index complet de la Bible",
		he: "אינדקס מלא של התנ",
		hu: "A Biblia teljes tárgymutatója",
		id: "Indeks Lengkap Alkitab",
		it: "Indice completo della Bibbia",
		ja: "聖書の完全な索引",
		ko: "성경 전체 색인",
		lt: "Pilna Biblijos rodyklė",
		nl: "Volledige index van de Bijbel",
		pl: "Pełny indeks Biblii",
		pt: "Índice Completo da Bíblia",
		ro: "Indexul complet al Bibliei",
		ru: "Полный индекс Библии",
		sv: "Fullständigt index över Bibeln",
		tr: "Tam İncil Dizini"
	},
	"frontpage": {
		bg: "Първа страница",
		cs: "Přední strana",
		da: "Forside",
		de: "Titelseite",
		el: "Εξώφυλλο",
		en: "Frontpage",
		es: "Portada",
		et: "Esilehekülg",
		fa: "صفحه اول",
		fi: "Etusivu",
		fr: "Page de garde",
		he: "עמוד ראשי",
		hu: "Címlap",
		id: "Halaman Depan",
		it: "Prima pagina",
		ja: "表紙",
		ko: "첫 장",
		lt: "Titulinis lapas",
		nl: "Voorpagina",
		pl: "Pierwsza strona",
		pt: "Primeira página",
		ro: "Prima pagina",
		ru: "Титульная страница",
		sv: "Framsida",
		tr: "Ön Sayfa"
	},
	"booksOther": {
		bg: "Други книги",
		cs: "Jiné knihy",
		da: "Andre bøger",
		de: "Andere Bücher",
		el: "Άλλα βιβλία",
		en: "Other books",
		es: "Otros libros",
		et: "Muud raamatud",
		fa: "کتاب های دیگر",
		fi: "Muut kirjat",
		fr: "Autres livres",
		he: "ספרים אחרים",
		hu: "Egyéb könyvek",
		id: "Buku-buku lain",
		it: "Altri libri",
		ja: "その他の書籍",
		ko: "다른 책들",
		lt: "Kitos knygos",
		nl: "Andere boeken",
		pl: "Inne książki",
		pt: "Outros livros",
		ro: "Alte cărți",
		ru: "Другие книги",
		sv: "Andra böcker",
		tr: "Diğer kitaplar"
	},
	"articles": {
		bg: "Статии",
		cs: "Články",
		da: "Artikler",
		de: "Artikel",
		el: "Άρθρα",
		en: "Articles",
		es: "Artículos",
		et: "Artiklid",
		fa: "مقالات",
		fi: "Artikkelit",
		fr: "Articles",
		he: "מאמרים",
		hu: "Cikkek",
		id: "Artikel",
		it: "Articoli",
		ja: "記事",
		ko: "조항",
		lt: "Straipsniai",
		nl: "Lidwoord",
		pl: "Artykuły",
		pt: "Artigos",
		ro: "Articole",
		ru: "Статьи",
		sv: "Artiklar",
		tr: "Nesne"
	},
	"study_aids": {
		bg: "Учебно помагало",
		cs: "Studijní pomůcka",
		da: "Studiehjælp",
		de: "Studienhilfe",
		el: "Βοήθημα μελέτης",
		en: "Study aids",
		es: "Ayudas de estudio",
		et: "Õpiabi",
		fa: "کمک تحصیلی",
		fi: "Opintotuki",
		fr: "Aide aux études",
		he: "סיוע לימודי",
		hu: "Tanulmányi segédlet",
		id: "Bantuan belajar",
		it: "Aiuto allo studio",
		ja: "学習補助",
		ko: "학습 보조",
		lt: "Pagalba studijoms",
		nl: "Studie hulp",
		pl: "Pomoc w nauce",
		pt: "Auxílio de estudo",
		ro: "Ajutor de studiu",
		ru: "Учебная помощь",
		sv: "Studiehjälp",
		tr: "Çalışma yardımı"
	},
	"topicIndexTitle_ALL": {
		bg: "Индекс на всички теми",
		cs: "Rejstřík všech témat",
		da: "Indeks over alle emner",
		de: "Index aller Themen",
		el: "Ευρετήριο όλων των θεμάτων",
		en: "Index of all topics",
		es: "Índice de todos términos",
		et: "Kõikide teemade register",
		fa: "فهرست همه موضوعات",
		fi: "Hakemisto kaikista aiheista",
		fr: "Index de tous les sujets",
		he: "אינדקס של כל הנושאים",
		hu: "Minden téma mutatója",
		id: "Indeks semua topik",
		it: "Indice di tutti gli argomenti",
		ja: "すべてのトピックのインデックス",
		ko: "모든 주제의 색인",
		lt: "Visų temų rodyklė",
		nl: "Index van alle onderwerpen",
		pl: "Indeks wszystkich tematów",
		pt: "Índice de todos os tópicos",
		ro: "Indexul tuturor subiectelor",
		ru: "Указатель всех тем",
		sv: "Index över alla ämnen",
		tr: "Tüm terimlerin indeksi"
	},
	"topicIndexTitle_PERSON": {
		bg: "Индекс на личности, хора, индивиди или групи и стари богове",
		cs: "Index osobností, lidí jednotlivců nebo skupin a starých bohů",
		da: "Indeks over personligheder, personer individer eller grupper og gamle guder",
		de: "Index von Persönlichkeiten, Menschen Einzelpersonen oder Gruppen und alten Göttern",
		el: "Ευρετήριο προσωπικοτήτων, ατόμων ατόμων ή ομάδων και παλιών θεών",
		en: "Index of personalities, people individuals or groups and old gods",
		es: "Índice de personalidades, personas individuales or colectivos y antiguos dioses",
		et: "Isiksuste, inimeste üksikisikute või rühmade ja vanade jumalate indeks",
		fa: "شاخص شخصیت ها، افراد افراد یا گروه ها و خدایان قدیمی",
		fi: "Indeksi persoonallisuuksista, ihmisistä yksilöistä tai ryhmistä ja vanhoista jumalista",
		fr: "Index des personnalités, personnes individus ou groupes et anciens dieux",
		he: "אינדקס אישים, אנשים יחידים או קבוצות ואלים ישנים",
		hu: "Személyiségek, emberek egyének vagy csoportok és régi istenek indexe",
		id: "Indeks kepribadian, orang individu atau kelompok dan dewa-dewa tua",
		it: "Indice di personalità, persone, individui o gruppi e antichi dei",
		ja: "性格、個人またはグループの人々、古い神々のインデックス",
		ko: "성격, 사람 개인 또는 그룹 및 고대 신의 색인",
		lt: "Asmenybių, žmonių individų ar grupių ir senųjų dievų rodyklė",
		nl: "Index van persoonlijkheden, mensen individuen of groepen en oude goden",
		pl: "Indeks osobowości, osób, osób lub grup i starych bogów",
		pt: "Índice de personalidades, pessoas, indivíduos ou grupos e deuses antigos",
		ro: "Index de personalități, oameni indivizi sau grupuri și zei vechi",
		ru: "Указатель личностей, людей, отдельных лиц или групп и старых богов",
		sv: "Register över personligheter, människor individer eller grupper och gamla gudar",
		tr: "Kişilikler, bireysel veya toplu kişiler ve eski tanrılar dizini"
	},
	"topicIndexTitle_PLACE": {
		bg: "Индекс на местата на Земята или във Вселената",
		cs: "Index míst, buď na Zemi nebo ve vesmíru",
		da: "Indeks over steder, enten på jorden eller på universet",
		de: "Index von Orten, entweder auf der Erde oder im Universum",
		el: "Ευρετήριο τόπων, είτε στη Γη είτε στο Σύμπαν",
		en: "Index of places, either on Earth or on the Universe",
		es: "Índice de lugares, tanto en la Tierra como en el Universo",
		et: "Kohtade indeks kas Maal või Universumis",
		fa: "فهرست مکان‌ها، چه روی زمین یا در کیهان",
		fi: "Paikkahakemisto joko maan päällä tai maailmankaikkeudessa",
		fr: "Index des lieux, soit sur Terre, soit dans l'Univers",
		he: "אינדקס של מקומות, על פני כדור הארץ או על היקום",
		hu: "Helyek indexe, akár a Földön, akár az Univerzumban",
		id: "Indeks tempat, baik di Bumi atau di Semesta",
		it: "Indice dei luoghi, sulla Terra o nell'Universo",
		ja: "地球上または宇宙上の場所のインデックス",
		ko: "지구 또는 우주의 장소 색인",
		lt: "Vietų Žemėje arba Visatoje indeksas",
		nl: "Index van plaatsen, op aarde of in het heelal",
		pl: "Indeks miejsc na Ziemi lub we Wszechświecie",
		pt: "Índice de lugares, seja na Terra ou no Universo",
		ro: "Indexul locurilor, fie pe Pământ, fie pe Univers",
		ru: "Указатель мест на Земле или во Вселенной",
		sv: "Index över platser, antingen på jorden eller på universum",
		tr: "Hem Dünyadaki hem de Evrendeki yerlerin indeksi"
	},
	"topicIndexTitle_ORDER": {
		bg: "Индекс на разредите и видовете същества",
		cs: "Index řádů a typů bytostí",
		da: "Indeks over ordrer og typer af væsener",
		de: "Verzeichnis der Ordnungen und Wesensarten",
		el: "Ευρετήριο τάξεων και τύπων όντων",
		en: "Index of orders and types of beings",
		es: "Índice de órdenes y tipologías de seres",
		et: "Järjestuste ja olendite tüüpide indeks",
		fa: "فهرست دستورات و انواع موجودات",
		fi: "Luokkien ja olentotyyppien hakemisto",
		fr: "Index des ordres et des types d'êtres",
		he: "אינדקס סדרים וסוגי ישויות",
		hu: "Rendek és lénytípusok mutatója",
		id: "Indeks pesanan dan jenis makhluk",
		it: "Indice di ordini e tipi di esseri",
		ja: "注文と存在の種類のインデックス",
		ko: "질서와 존재 유형의 색인",
		lt: "Įsakymų ir būtybių tipų rodyklė",
		nl: "Index van orden en soorten wezens",
		pl: "Indeks rzędów i typów istot",
		pt: "Índice de ordens e tipos de seres",
		ro: "Indice de ordine și tipuri de ființe",
		ru: "Указатель порядков и типов существ",
		sv: "Index över beställningar och typer av varelser",
		tr: "Varlıkların düzenleri ve tipolojileri dizini"
	},
	"topicIndexTitle_RACE": {
		bg: "Индекс на раси, племена или народи",
		cs: "Index ras, kmenů nebo národů",
		da: "Indeks over racer, stammer eller folk",
		de: "Index von Rassen, Stämmen oder Völkern",
		el: "Ευρετήριο φυλών, φυλών ή λαών",
		en: "Index of races, tribes or peoples",
		es: "Índice de razas, tribus o pueblos",
		et: "Rasside, hõimude või rahvaste indeks",
		fa: "فهرست نژادها، قبایل یا مردم",
		fi: "Rotujen, heimojen tai kansojen hakemisto",
		fr: "Index des races, tribus ou peuples",
		he: "אינדקס של גזעים, שבטים או עמים",
		hu: "A fajok, törzsek vagy népek indexe",
		id: "Indeks ras, suku atau bangsa",
		it: "Indice di razze, tribù o popoli",
		ja: "人種、部族または民族のインデックス",
		ko: "인종, 부족 또는 민족의 색인",
		lt: "Rasių, genčių ar tautų indeksas",
		nl: "Index van rassen, stammen of volkeren",
		pl: "Indeks ras, plemion lub ludów",
		pt: "Índice de raças, tribos ou povos",
		ro: "Index de rase, triburi sau popoare",
		ru: "Указатель рас, племен или народов",
		sv: "Index över raser, stammar eller folk",
		tr: "Irklar, kabileler veya halklar dizini"
	},
	"topicIndexTitle_RELIGION": {
		bg: "Индекс на религии, култове, вярвания",
		cs: "Index náboženství, kultů, přesvědčení",
		da: "Indeks over religioner, kulter, tro",
		de: "Index der Religionen, Kulte, Überzeugungen",
		el: "Ευρετήριο θρησκειών, λατρειών, πεποιθήσεων",
		en: "Index of religions, cults, beliefs",
		es: "Índice de religiones, cultos, creencias",
		et: "Religioonide, kultuste, uskumuste register",
		fa: "فهرست ادیان، فرقه ها، عقاید",
		fi: "Uskontojen, kulttien, uskomusten hakemisto",
		fr: "Index des religions, cultes, croyances",
		he: "אינדקס של דתות, כתות, אמונות",
		hu: "Vallások, kultuszok, hiedelmek mutatója",
		id: "Indeks agama, kultus, kepercayaan",
		it: "Indice di religioni, culti, credenze",
		ja: "宗教、カルト、信念のインデックス",
		ko: "종교, 컬트, 신념의 색인",
		lt: "Religijų, kultų, tikėjimų rodyklė",
		nl: "Index van religies, sekten, overtuigingen",
		pl: "Indeks religii, kultów, wierzeń",
		pt: "Índice de religiões, cultos, crenças",
		ro: "Index de religii, culte, credințe",
		ru: "Указатель религий, культов, верований",
		sv: "Index över religioner, kulter, övertygelser",
		tr: "Dinler, kültler, inançlar endeksi"
	},
	"indexAll": {
		bg: "Списък на всички индекси",
		cs: "Seznam všech indexů",
		da: "Liste over alle indekser",
		de: "Liste aller Indizes",
		el: "Λίστα όλων των Ευρετηρίων",
		en: "List of all Indexes",
		es: "Listado de todos los Índices",
		et: "Kõigi indeksite loend",
		fa: "فهرست همه شاخص ها",
		fi: "Luettelo kaikista indekseistä",
		fr: "Liste de tous les index",
		he: "רשימת כל האינדקסים",
		hu: "Az összes index listája",
		id: "Daftar semua Indeks",
		it: "Elenco di tutti gli indici",
		ja: "すべてのインデックスのリスト",
		ko: "모든 인덱스 목록",
		lt: "Visų indeksų sąrašas",
		nl: "Lijst met alle indexen",
		pl: "Lista wszystkich indeksów",
		pt: "Lista de todos os índices",
		ro: "Lista tuturor indicilor",
		ru: "Список всех индексов",
		sv: "Lista över alla index",
		tr: "Tüm Dizinlerin Listesi"
	},
	"indexAllDesc": {
		bg: "Ето списък на всички индекси, съдържащи се в Урантиапедия, организирани по групи от съдържание.",
		cs: "Zde je seznam všech indexů obsažených v Urantiapedii, uspořádaných podle skupin obsahu.",
		da: "Zde je seznam všech indexů obsažených v Urantiapedii, uspořádaných podle skupin obsahu.",
		de: "Hier ist eine Liste aller Indizes, die in Urantiapedia enthalten sind, geordnet nach Inhaltsgruppen.",
		el: "Ακολουθεί μια λίστα με όλα τα ευρετήρια που περιέχονται στην Urantiapedia, οργανωμένα ανά ομάδες περιεχομένων.",
		en: "Here is a list of all the indexes contained in Urantiapedia, organized by groups of contents.",
		es: "Aquí se ofrece una lista de todos los índices contenidos en la Urantiapedia, organizados por grupos de contenidos.",
		et: "Siin on loetelu kõigist Urantiapedias sisalduvatest registritest sisurühmade kaupa.",
		fa: "در اینجا فهرستی از تمام نمایه‌های موجود در Urantiapedia است که بر اساس گروه‌هایی از مطالب سازمان‌دهی شده‌اند.",
		fi: "Tässä on luettelo kaikista Urantiapedian hakemistoista sisältöryhmittäin järjestettynä.",
		fr: "Voici une liste de tous les index contenus dans Urantiapedia, organisés par groupes de contenus.",
		he: "הנה רשימה של כל האינדקסים הכלולים ב-Urantiapedia, מאורגנת לפי קבוצות תוכן.",
		hu: "Itt található az Urantiapedia összes indexének listája, tartalomcsoportok szerint rendezve.",
		id: "Berikut adalah daftar semua indeks yang terdapat di Urantiapedia, disusun menurut kelompok konten.",
		it: "Ecco un elenco di tutti gli indici contenuti in Urantiapedia, organizzati per gruppi di contenuti.",
		ja: "これは、Urantiapedia に含まれるすべての索引のリストであり、コンテンツのグループごとに編成されています。",
		ko: "다음은 콘텐츠 그룹으로 구성된 Urantiapedia에 포함된 모든 색인의 목록입니다.",
		lt: "Čia yra visų Urantiapedijoje esančių indeksų sąrašas, suskirstytas pagal turinio grupes.",
		nl: "Hier is een lijst van alle indexen in Urantiapedia, geordend op inhoudsgroepen.",
		pl: "Oto lista wszystkich indeksów zawartych na Urantiapedii, uporządkowanych według grup treści.",
		pt: "Aqui está uma lista de todos os índices contidos em Urantiapedia, organizados por grupos de conteúdos.",
		ro: "Iată o listă cu toți indexurile conținute în Urantiapedia, organizate pe grupuri de conținut.",
		ru: "Вот список всех указателей, содержащихся в Урантиапедии, организованный по группам содержания.",
		sv: "Här är en lista över alla index som finns i Urantiapedia, organiserade efter innehållsgrupper.",
		tr: "Burada, içerik grupları tarafından düzenlenen Urantiapedia'da yer alan tüm dizinlerin bir listesi bulunmaktadır."
	},
	"indexAllBooks": {
		bg: "Книги",
		cs: "Knihy",
		da: "Bøger",
		de: "Bücher",
		el: "Βιβλία",
		en: "Books",
		es: "Libros",
		et: "Raamatud",
		fa: "کتاب ها",
		fi: "Kirjat",
		fr: "Livres",
		he: "ספרים",
		hu: "Könyvek",
		id: "Buku",
		it: "Libri",
		ja: "書籍",
		ko: "서적",
		lt: "Knygos",
		nl: "Boeken",
		pl: "Książki",
		pt: "Livros",
		ro: "Cărți",
		ru: "Книги",
		sv: "Böcker",
		tr: "Kitabın"
	},
	"lblOpenMap": {
		bg: "Отворете картата",
		cs: "Otevřít mapu",
		da: "Åbn kort",
		de: "Karte öffnen",
		el: "Άνοιγμα χάρτη",
		en: "Open map",
		es: "Abrir mapa",
		et: "Ava kaart",
		fa: "نقشه را باز کنید",
		fi: "Avaa kartta",
		fr: "Ouvrir la carte",
		he: "פתח את המפה",
		hu: "Nyissa meg a térképet",
		id: "Buka peta",
		it: "Apri mappa",
		ja: "地図を開く",
		ko: "지도 열기",
		lt: "Atidaryti žemėlapį",
		nl: "Kaart openen",
		pl: "Otwórz mapę",
		pt: "Abrir mapa",
		ro: "Deschide harta",
		ru: "Открыть карту",
		sv: "Öppna kartan",
		tr: "Haritayı aç"
	},
	"quotationStart": {
		bg: "„",
		cs: "„",
		da: "»",
		de: "„",
		el: "«",
		en: "“",
		es: "«",
		et: "„",
		fa: "«",
		fi: "”",
		fr: "« ",
		he: "”",
		hu: "„",
		id: "“",
		it: "«",
		ja: "「",
		ko: "“",
		lt: "„",
		nl: "“",
		pl: "„",
		pt: "«",
		ro: "„",
		ru: "«",
		sv: "”",
		tr: "“"
	},
	"quotationEnd": {
		bg: "“",
		cs: "“",
		da: "«",
		de: "“",
		el: "»",
		en: "”",
		es: "»",
		et: "“",
		fa: "»",
		fi: "”",
		fr: " »",
		he: "”",
		hu: "”",
		id: "”",
		it: "»",
		ja: "」",
		ko: "”",
		lt: "“",
		nl: "”",
		pl: "”",
		pt: "»",
		ro: "”",
		ru: "»",
		sv: "”",
		tr: "”"
	},
	"articlesSource": {
		en: "Source",
		es: "Fuente",
		fr: "Source"
	},
	"lblLanguage": {
		en: "Urantiapedia Language:",
		es: "Idioma de la Urantiapedia:"
	},
	"lblUILanguage": {
		en: "UI Language:",
		es: "Idioma interfaz:"
	},
	"lblSettings": {
		en: "Settings",
		es: "Configuración"
	},
	"lblSearch": {
		en: "Search",
		es: "Buscar"
	},
	"lblTheme": {
		en: "Theme:",
		es: "Tema:"
	},
	"lblProcess": {
		en: "Process:",
		es: "Proceso:"
	},
	"exeButton": {
		en: "Execute",
		es: "Ejecutar"
	},
	"lblTTextbox": {
		en: "TXT files:",
		es: "Ficheros TXT:"
	},
	"dirTTextbox": {
		en: "Browse path",
		es: "Selecciona la ruta"
	},
	"dirTButton": {
		en: "Browse",
		es: "Seleccionar"
	},
	"lblHTextbox": {
		en: "HTML files:",
		es: "Ficheros HTML:"
	},
	"dirHTextbox": {
		en: "Browse path",
		es: "Selecciona la ruta"
	},
	"dirHButton": {
		en: "Browse",
		es: "Seleccionar"
	},
	"lblLTextbox": {
		en: "LaTeX files:",
		es: "Ficheros LaTeX:"
	},
	"dirLTextbox": {
		en: "Browse path",
		es: "Selecciona la ruta"
	},
	"dirLButton": {
		en: "Browse",
		es: "Seleccionar"
	},
	"lblJTextbox": {
		en: "JSON files:",
		es: "Ficheros JSON:"
	},
	"dirJTextbox": {
		en: "Browse path",
		es: "Selecciona la ruta"
	},
	"dirJButton": {
		en: "Browse",
		es: "Seleccionar"
	},
	"lblWTextbox": {
		en: "Wiki files:",
		es: "Ficheros Wiki:"
	},
	"dirWTextbox": {
		en: "Browse path",
		es: "Selecciona la ruta"
	},
	"dirWButton": {
		en: "Browse",
		es: "Seleccionar"
	},
	"chkMergeLabel": {
		en: "Join output files in one",
		es: "Unir los ficheros de salida en uno"
	},
	"lblCategories": {
		en: "Topic categories",
		es: "Categorías de términos"
	},
	"lblTICategories": {
		en: "Topic categories",
		es: "Categorías de términos"
	},
	"lblTopics": {
		en: "Topic (execute to fill)",
		es: "Término (ejecuta para rellenar)"
	},
	"collapseButton": {
		en: "Show/hide controls",
		es: "Mostrar/ocultar controles"
	},
	"lblProccesses": {
		en: "Proccesses",
		es: "Procesos"
	},
	"lblTopicIndex": {
		en: "Edit Topic Index",
		es: "Editar Términos"
	},
	"lblTopicName": {
		en: "Name",
		es: "Nombre"
	},
	"lblTILanguage1": {
		en: "Main Language (to modify)",
		es: "Idioma Principal (a modificar)"
	},
	"lblTILanguage2": {
		en: "Secondary Language",
		es: "Idioma Secundario"
	},
	"lblTIName": {
		en: "Name",
		es: "Nombre"
	},
	"lblTIAliases": {
		en: "Aliases",
		es: "Aliases"
	},
	"lblTIRevised": {
		en: "Revised",
		es: "Revisado"
	},
	"lblTIRefs": {
		en: "Refs",
		es: "Refs"
	},
	"lblTISeeAlso": {
		en: "See Also",
		es: "Ver También"
	},
	"lblTILinks": {
		en: "Links",
		es: "Enlaces"
	},
	"lblTICategory": {
		en: "Category",
		es: "Categoría"
	},
	"lblTILines": {
		en: "Topic content & errors",
		es: "Contenido de los términos & errores"
	},
	"lblTIUBLines": {
		en: "The Urantia Book content",
		es: "Contenido de El Libro de Urantia"
	},
	"lblTILetters": {
		en: "Topic letters",
		es: "Letras de términos"
	},
	"btnTILoadTopics": {
		en: "Load topics",
		es: "Cargar términos"
	},
	"btnTILoadTopics_loading": {
		en: "Loading...",
		es: "Cargando..."
	},
	"lblTIFilterRevised": {
		en: "Non-Revised",
		es: "No-Revisados"
	},
	"lblTIFilterErrors": {
		en: "With errors",
		es: "Con errores"
	},
	"btnSearch": {
		en: "Search",
		es: "Buscar"
	},
	"btnSearch_searching": {
		en: "Searching...",
		es: "Buscando..."
	},
	"btnAddQuotes": {
		en: "Add Quotes to Files",
		es: "Añadir Citas a Ficheros"
	},
	"btnAddQuotes_adding": {
		en: "Adding...",
		es: "Añadiendo..."
	},
	"strSelectFile": {
		en: "Select file",
		es: "Selecciona fichero"
	},
	"strSelectFolder": {
		en: "Select folder",
		es: "Selecciona carpeta"
	},
	"book_wrong_reference": {
		en: "UB reference {0} is wrong or not exists",
		es: "La referencia LU {0} está mal o no existe"
	},
	"book_wrong_footnotes": {
		en: "Error extracting subfootnotes",
		es: "Error extrayendo subfootnotes"
	},
	"book_no_sections": {
		en: "{0}: The paper has no sections",
		es: "{0}: El documento no tiene secciones"
	},
	"book_section_no_reference": {
		en: "{0}: A section has no reference",
		es: "{0}: Una sección no tiene referencia"
	},
	"book_section_no_pars": {
		en: "{0}: A section has no paragraphs",
		es: "{0}: Una sección no tiene párrafos"
	},
	"book_paper_no_title": {
		en: "{0}: Paper has no title",
		es: "{0}: El documento no tiene título"
	},
	"book_par_no_refcontent": {
		en: "{0}: A paragraph has no reference or content",
		es: "{0}: Un párafo no tiene referencia o contenido"
	},
	"book_tag_no_closing": {
		en: "{0}, line {1}: No correct closing string exists",
		es: "{0}, línea {1}: No existe cadena de cierre correcto"
	},
	"book_no_paper_index": {
		en: "{0}, line {1}: Filename do not contains paper index",
		es: "{0}, línea {1}: El nombre de archivo no contiene el número de documento"
	},
	"book_no_paper_start": {
		en: "{0}, line {1}: Cannot extract start tag of paper",
		es: "{0}, línea {1}: No se pudo extraer etiqueta de inicio del documento"
	},
	"book_no_section_start": {
		en: "{0}, line {1}: Cannot extract start tag of section",
		es: "{0}, línea {1}: No se pudo extraer etiqueta de inicio de sección"
	},
	"book_no_pageref": {
		en: "{0}, line {1}: Cannot extract reference of type page",
		es: "{0}, línea {1}: No se pudo extraer la referencia tipo página"
	},
	"book_no_parref": {
		en: "{0}, line {1}: Cannota extract paragraph reference",
		es: "{0}, línea {1}: No se pudo extraer la referencia de párrafo"
	},
	"book_no_add_par": {
		en: "{0}, line {1}: Cannot add paragraph without a previous section",
		es: "{0}, línea {1}: No se pudo añadir párrafo sin una sección previa"
	},
	"book_no_ref_previous": {
		en: "{0}, line {1}: Reference of type page do not exist in previous line",
		es: "{0}, línea {1}: No existe en línea previa la referencia tipo página"
	},
	"book_no_closing_footnote": {
		en: "{0}, line {1}: Closing footnote tag not found",
		es: "{0}, línea {1}: No existe cierre de nota al pie correcto"
	},
	"book_paper_not_found": {
		en: "Paper {0} not found",
		es: "Documento {0} no encontrado."
	},
	"book_section_not_found": {
		en: "Section {0} not found",
		es: "Sección {0} no encontrada."
	},
	"book_invalid_number": {
		en: "Invalid number of items in paper {0}",
		es: "Número de items no válido en doc {0}"
	},
	"book_par_not_found": {
		en: "Paragraph not found {0} in paper {1}",
		es: "Párrafo no encontrado {0} en doc {1}"
	},
	"book_error_footnotes": {
		en: "{0}: Error in footnotes: {1}",
		es: "{0}: Error en notas al pie: {1}"
	},
	"book_item_no_found": {
		en: "{0} not found in {1}",
		es: "{0} no encontrado en {1}"
	},
	"book_no_valid_reference": {
		en: "{0}: Reference is not valid in {1}",
		es: "{0}: La referencia no es válida en {1}"
	},
	"bible_no_title": {
		en: "{0}, line {1}: Cannot extract book title",
		es: "{0}, línea {1}: No se pudo extraer el título del libro"
	},
	"bible_title_invalid": {
		en: "{0}, line {1}: Book title is not valid",
		es: "{0}, línea {1}: El título del libro no es válido"
	},
	"bible_no_chapter": {
		en: "{0}, line {1}: Cannot extract chapter",
		es: "{0}, línea {1}: No se pudo extraer el capítulo"
	},
	"bible_no_section": {
		en: "{0}, line {1}: Cannot extract section",
		es: "{0}, línea {1}: No se pudo extraer la sección"
	},
	"bible_section_order": {
		en: "{0}, line {1}: Section before chapter?",
		es: "{0}, línea {1}: Sección antes de capítulo?"
	},
	"bible_chapter_not_found": {
		en: "{0}, chapter {1}: Chapter title is not found",
		es: "{0}, capítulo {1}: El capítulo no se encuentra"
	},
	"bible_chapter_missing_verses": {
		en: "{0}, chapter {1}: Chapter has some missing verses: {2}",
		es: "{0}, capítulo {1}: El capítulo no tiene algunos versículos: {2}"
	},
	"bible_chapter_wrong_italics": {
		en: "{0}, chapter {1}: Chapter has some wrong italics: {2}",
		es: "{0}, capítulo {1}: El capítulo tiene cursivas erróneas: {2}"
	},
	"dir_no_access": {
		en: "{0}, line {1}: Folder {0} not accessible",
		es: "{0}, línea {1}: El directorio {0} no está accesible"
	},
	"bibleref_bookname_invalid": {
		en: "{0}, line {1}: Book name is no valid",
		es: "{0}, línea {1}: Nombre del libro no es válido"
	},
	"bibleref_no_data": {
		en: "{0}, line {1}: There is no enough data in reference",
		es: "{0}, línea {1}: No hay suficientes datos en la referencia"
	},
	"bibleref_bad_ref": {
		en: "{0}, line {1}: Bad Bible reference",
		es: "{0}, línea {1}: La referencia de la Biblia está mal"
	},
	"bibleref_bad_ub_ref": {
		en: "{0}, line {1}: Bad Urantia Book reference",
		es: "{0}, línea {1}: La referencia de El Libro de Urantia está mal"
	},
	"bibleref_bad_number": {
		en: "{0}, line {1}: Chapter or verse number is bad",
		es: "{0}, línea {1}: El número de capítulo o versículo está mal"
	},
	"topic_en_required": {
		en: "{0}: Topic Index in english must be provided",
		es: "{0}: El Índide de Términos en inglés debe proporcionarse"
	},
	"topic_err": {
		en: "{0}, line {1}: {2}",
		es: "{0}, línea {1}: {2}"
	},
	"topic_duplicated": {
		en: "topic duplicated in ",
		es: "término duplicado en "
	},
	"topic_invalid_refs": {
		en: "invalid references: ",
		es: "referencias inválidas: "
	},
	"topic_not_in_ref": {
		en: "'{0}' in no ref: {1}",
		es: "'{0}' en ninguna ref: {1}"
	},
	"topic_in_less_20%": {
		en: "'{0}' is not in these refs (less than 20%): {1}",
		es: "'{0}' no está en estas refs (menos del 20%): {1}"
	},
	"topic_invalid_see": {
		en: "'{0}': topic has different seeAlso in english",
		es: "'{0}': el término tiene diferentes seeAlso en inglés"
	},
	"topic_en_not_found": {
		en: "'{0}' not found in english",
		es: "'{0}' no encontrado en inglés"
	},
	"topic_seealso_not_found": {
		en: "seeAlso '{0}' not found",
		es: "seeAlso '{0}' no encontrado"
	},
	"topic_err_writing": {
		en: "Error writing topic index: {0}",
		es: "Error guardando el índice de términos: {0}"
	},
	"topic_see_also": {
		bg: "Вижте също",
		cs: "Viz také",
		da: "Se også",
		de: "Siehe auch",
		el: "Δείτε επίσης",
		en: "See also",
		es: "Véase también",
		et: "Vaata ka",
		fa: "همچنین ببینید",
		fi: "Katso myös",
		fr: "Voir aussi",
		he: "ראה גם",
		hu: "Lásd még",
		id: "Lihat juga",
		it: "Voci correlate",
		ja: "も参照してください",
		ko: "또한보십시오",
		lt: "Taip pat žr",
		nl: "Zie ook",
		pl: "Zobacz też",
		pt: "Ver também",
		ro: "Vezi si",
		ru: "Смотрите также",
		sv: "Se även",
		tr: "Ayrıca bakınız"
	},
	"topic_links": {
		bg: "връзки",
		cs: "Odkazy",
		da: "Links",
		de: "Links",
		el: "Σύνδεσμοι",
		en: "Links",
		es: "Enlaces",
		et: "Lingid",
		fa: "پیوندها",
		fi: "Linkkejä",
		fr: "Liens",
		he: "קישורים",
		hu: "Linkeket",
		id: "Link",
		it: "Collegamenti",
		ja: "リンク",
		ko: "연결",
		lt: "Nuorodos",
		nl: "Links",
		pl: "Spinki do mankietów",
		pt: "Ligações",
		ro: "Link-uri",
		ru: "ссылки",
		sv: "Länkar",
		tr: "Bağlantılar"
	},
	"topic_external_links": {
		bg: "външни връзки",
		cs: "Externí odkazy",
		da: "Eksterne links",
		de: "Externe Links",
		el: "Εξωτερικοί σύνδεσμοι",
		en: "External links",
		es: "Enlaces externos",
		et: "Välised lingid",
		fa: "لینک های خارجی",
		fi: "Ulkoiset linkit",
		fr: "Liens externes",
		he: "קישורים חיצוניים",
		hu: "Külső linkek",
		id: "Tautan eksternal",
		it: "Collegamenti esterni",
		ja: "外部リンク",
		ko: "외부 링크",
		lt: "Išorinės nuorodos",
		nl: "Externe links",
		pl: "Zewnętrzne linki",
		pt: "Ligações externas",
		ro: "Linkuri externe",
		ru: "внешние ссылки",
		sv: "Externa länkar",
		tr: "Dış bağlantılar"
	},
	"topic_references": {
		bg: "препратки",
		cs: "Reference",
		da: "Referencer",
		de: "Verweise",
		el: "Παραπομπές",
		en: "References",
		es: "Referencias",
		et: "Viited",
		fa: "منابع",
		fi: "Viittauksia",
		fr: "Références",
		he: "הפניות",
		hu: "Hivatkozások",
		id: "Referensi",
		it: "Riferimenti",
		ja: "参照",
		ko: "참조",
		lt: "Nuorodos",
		nl: "Referenties",
		pl: "Bibliografia",
		pt: "Referências",
		ro: "Referințe",
		ru: "использованная литература",
		sv: "Referenser",
		tr: "Referanslar"
	},
	"topicindex_save_confirm": {
		en: "Save changes to Topic Index?",
		es: "¿Guardar cambios al Índice de Términos?"
	},
	"article_bad_title": {
		en: "Article title is not correct",
		es: "El título del artículo no es correcto"
	},
	"article_index_no_lines": {
		en: "Article index has no lines",
		es: "Índice de artículos sin líneas"
	},
	"article_index_missing_data": {
		en: "Article index missing data in line {0}",
		es: "Índice de artículos requiere datos en línea {0}"
	},
	"article_index_no_issues": {
		en: "Article index has no issues",
		es: "Índice de artículos no tiene números de revista"
	},
	"article_has_no_copyright_card": {
		en: "Article has no copyright card: {0}",
		es: "El artículo no tiene nota de copyright: {0}"
	},
	"folder_no_access": {
		en: "Folder {0} is not accessible",
		es: "El directorio {0} no está accesible"
	},
	"folder_name_invalid": {
		en: "Folder {0} contains blank spaces or invalid chars",
		es: "El directorio {0} contiene espacios en blanco o caracteres no válidos",
	},
	"folder_not_exists": {
		en: "Folder {0} not exists",
		es: "El directorio {0} no existe"
	},
	"file_not_exists": {
		en: "File {0} not exists",
		es: "El fichero {0} no existe"
	},
	"files_not_with_format": {
		en: "Files with format {0} not found",
		es: "No se han encontrado archivos {0}"
	},
	"proccessing": {
		en: "Proccessing file {0}",
		es: "Procesando fichero {0}"
	},
	"footnotes_folder_required": {
		en: "It is required create folder {0}-footnotes",
		es: "Es necesario crear la carpeta {0}-footnotes"
	},
	"folder_required": {
		en: "One input folder do not exists",
		es: "Falta uno de los directorios de entrada"
	},
	"success": {
		en: "Conversion executed successfully",
		es: "Conversión realizada con éxito"
	}
}

module.exports = Strings;